name: brandur CI

on:
  pull_request:
  push:
  schedule:
    # Once every 3 hours.
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install Go
        uses: actions/setup-go@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "go env GOPATH=$(go env GOPATH)"
          echo "pwd=$(pwd)"
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "HOME=${HOME}"

      - name: "Go: Test"
        run: go test ./...
        working-directory: ./updater

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh

      - name: "Generate README.md"
        run: OUT=$(go run main.go) && echo "$OUT" > ../README.md
        working-directory: ./updater

      - name: Commit and push (if changed)
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -u
          git commit -m "Automatic update from GitHub Action" || exit 0
          git push
        if: github.ref == 'refs/heads/master'
